risk_config:
  daily_max_loss_pct: 2.0
  daily_max_trades: 30
  default_stop_loss_pct: 4.0
  base_position_pct: 10.0
  max_positions: 7
  strategy_allocation:
    momentum_breakout: 35.0
    theme_chasing: 5.0
    sepa_trend: 50.0
    gap_and_go: 5.0
    rsi2_reversal: 5.0
exit_manager:
  max_stop_pct: 6.0
  min_stop_pct: 3.0
  first_exit_pct: 2.5
  first_exit_ratio: 0.3
  stop_loss_pct: 2.5
  trailing_activate_pct: 3.0
  trailing_stop_pct: 2.5
momentum_breakout:
  enabled: true
  stop_loss_pct: 3.5
  min_volume_ratio: 2.5
  trading_start_time: '10:30'
  min_score: 75.0
  min_breakout_pct: 0.8
theme_chasing:
  stop_loss_pct: 2.5
  min_volume_ratio: 2.3
  trading_start_time: 09:10
  entry_window_minutes: 20
gap_and_go:
  stop_loss_pct: 2.5
  min_volume_ratio: 3.0
sepa_trend:
  weight: 60
  min_score: 60
_meta:
  exit_manager.stop_loss_pct:
    source: llm
    timestamp: '2026-02-11T20:31:33.438158'
  risk_config.strategy_allocation:
    source: weekly_rebalance
    timestamp: '2026-02-21T00:00:34.666905'
