risk_config:
  daily_max_loss_pct: 2.0
  base_position_pct: 7.0
  max_position_pct: 15.0
  default_stop_loss_pct: 1.3
  daily_max_trades: 4
  hot_theme_position_pct: 25.0
  min_cash_reserve_pct: 20.0
exit_manager:
  stop_loss_pct: 1.3
  first_exit_pct: 1.6
  first_exit_ratio: 0.5
  second_exit_pct: 3.0
  trailing_activate_pct: 1.8
  trailing_stop_pct: 1.0
